### ISSUE TITLE
Repository should have a changelog file

### ISSUE THREAD

**Issue by cabello** [disqus/toronado#17]
Hi, first let me say thank you for providing a simple solution that just works. :smile_cat: 

I am upgrading toronado on a project from 0.0.6 to 0.0.7 and the only way to know what changed is skimming through commits. A file with a summary of the changes would be great.

Here is a list of packages that I just upgraded to serve as inspiration:
- https://github.com/celery/billiard/blob/master/CHANGES.txt
- https://github.com/mbi/django-rosetta/blob/develop/CHANGES
- http://www.fabfile.org/changelog.html
- https://github.com/joke2k/faker/blob/master/CHANGELOG.rst
- https://github.com/celery/kombu/blob/v3.0.26/Changelog
- https://bitbucket.org/izi/polib/src/fe6d3a5da22f0ae72bf234ec45edf2909aac9170/CHANGELOG?at=default
- https://github.com/linsomniac/python-memcached/blob/master/ChangeLog
- https://github.com/andialbrecht/sqlparse/blob/master/CHANGES

You can see there is no de facto standard for the file name: `CHANGES.txt`, `CHANGES`, `changelog.html`, `CHANGELOG.rst` nor the file content, but the summary provide valuable insight on the update.

Thanks.

**Comment by tkaemming** [comment]
Started tracking changes with 6f672c9c160f5ede6f606a2b99a031447db5234d.
